// SPDX-License-Identifier: MIT
//
// ClipboardItemRowView+Preview.swift
// Clipboard - Clipboard Item Row View Extension Contract
//
// This file defines the interface extension for the ClipboardItemRowView
// to support preview panel hover detection.
// Generated by /speckit.plan command for feature 001-clipboard-preview-panel.

import SwiftUI

/// 剪贴板列表行视图（预览扩展）
///
/// 职责扩展：
/// - 检测鼠标悬停事件
/// - 通知 ViewModel 悬停状态变化
/// - 管理悬停定时器
///
/// 依赖：
/// - ClipboardHistoryViewModel: 接收悬停事件
extension ClipboardItemRowView {

    /// 悬停检测修饰符（添加到现有视图）
    func previewHoverDetection(item: ClipboardItem, viewModel: ClipboardHistoryViewModel) -> some View {
        self.onHover { isHovering in
            if isHovering {
                viewModel.onItemHovered(item)
            } else {
                viewModel.onItemExited()
            }
        }
    }
}

// MARK: - Integration Example

/*
 在 ClipboardItemRowView 的 body 中添加：

 var body: some View {
     HStack {
         // 现有内容
     }
     .previewHoverDetection(item: item, viewModel: viewModel)
 }
 */

// MARK: - Focus Management Extension

extension ClipboardItemRowView {

    /// 焦点绑定（用于键盘导航）
    func focusManagement(isFocused: Binding<Bool>, item: ClipboardItem, viewModel: ClipboardHistoryViewModel) -> some View {
        self
            .focused($isFocused.wrappedValue)
            .onChange(of: isFocused.wrappedValue) { _, newValue in
                if newValue {
                    viewModel.onItemFocused(item)
                }
            }
    }
}

// MARK: - Hover State Tracking

/// 悬停状态跟踪器（可选的独立组件）
@Observable
class HoverStateTracker {
    var currentHoveredItem: ClipboardItem?
    var hoverStartTime: Date?

    private var hoverTimer: Timer?

    /// 开始悬停计时
    func startHover(for item: ClipboardItem, delay: TimeInterval = 0.2, completion: @escaping () -> Void) {
        currentHoveredItem = item
        hoverStartTime = Date()

        hoverTimer?.invalidate()
        hoverTimer = Timer.scheduledTimer(withTimeInterval: delay, repeats: false) { [weak self] _ in
            if self?.currentHoveredItem?.id == item.id {
                completion()
            }
        }
    }

    /// 取消悬停
    func cancelHover() {
        hoverTimer?.invalidate()
        hoverTimer = nil
        currentHoveredItem = nil
        hoverStartTime = nil
    }

    /// 是否正在悬停
    var isHovering: Bool {
        currentHoveredItem != nil
    }
}
