// SPDX-License-Identifier: MIT
//
// PreviewPanelView.swift
// Clipboard - Preview Panel Component Contract
//
// This file defines the interface contract for the PreviewPanelView component.
// Generated by /speckit.plan command for feature 001-clipboard-preview-panel.

import SwiftUI

/// 预览面板主视图
///
/// 职责：
/// - 根据剪贴板项类型显示不同的预览内容
/// - 管理面板的显示/隐藏动画
/// - 处理面板的定位（左右切换）
///
/// 依赖：
/// - PreviewPanelViewModel: 提供预览状态和内容
struct PreviewPanelView: View {

    // MARK: - Properties

    /// 视图模型，提供预览状态和内容
    @ObservedController var viewModel: PreviewPanelViewModel

    /// 面板是否显示在左侧（否则在右侧）
    var shouldShowOnLeft: Bool = false

    /// 面板尺寸（固定 300x300）
    var panelSize: CGSize = .init(width: 300, height: 300)

    // MARK: - Body

    var body: some View {
        Group {
            switch viewModel.panelState {
            case .hidden:
                EmptyView()
            case .showing(let item):
                previewContent(for: item)
            case .loading:
                loadingView
            case .error(let message):
                errorView(message)
            }
        }
        .frame(width: panelSize.width, height: panelSize.height)
        .background(DesignSystem.PreviewPanel.background)
        .cornerRadius(DesignSystem.PreviewPanel.cornerRadius)
        .shadow(
            color: DesignSystem.PreviewPanel.shadowColor,
            radius: DesignSystem.PreviewPanel.shadowRadius,
            x: DesignSystem.PreviewPanel.shadowX,
            y: DesignSystem.PreviewPanel.shadowY
        )
        .overlay(
            RoundedRectangle(cornerRadius: DesignSystem.PreviewPanel.cornerRadius)
                .stroke(DesignSystem.PreviewPanel.borderColor, lineWidth: 1)
        )
        .opacity(viewModel.panelState == .hidden ? 0 : 1)
        .animation(.easeInOut(duration: 0.15), value: viewModel.panelState)
        .padding(.trailing, shouldShowOnLeft ? 0 : 16)
        .padding(.leading, shouldShowOnLeft ? 16 : 0)
    }

    // MARK: - Private Views

    @ViewBuilder
    private func previewContent(for item: ClipboardItem) -> some View {
        switch item.type {
        case .text:
            PreviewTextView(item: item)
        case .image:
            PreviewImageView(item: item)
        case .file:
            PreviewFileView(item: item)
        }
    }

    private var loadingView: some View {
        VStack(spacing: 12) {
            ProgressView()
                .scaleEffect(1.2)
            Text("加载中...")
                .font(DesignSystem.Typography.caption)
                .foregroundColor(DesignSystem.Colors.secondaryText)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    private func errorView(_ message: String) -> some View {
        VStack(spacing: 12) {
            Image(systemName: "exclamationmark.triangle")
                .font(.system(size: 48))
                .foregroundColor(DesignSystem.Colors.error)
            Text(message)
                .font(DesignSystem.Typography.caption)
                .foregroundColor(DesignSystem.Colors.secondaryText)
                .multilineTextAlignment(.center)
                .padding(.horizontal, 20)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }
}

// MARK: - Preview

#Preview {
    PreviewPanelView(
        viewModel: PreviewPanelViewModel.preview
    )
}

// MARK: - Design System Extension

extension DesignSystem {
    enum PreviewPanel {
        static let background = Color(nsColor: .windowBackgroundColor)
        static let cornerRadius: CGFloat = 12
        static let borderColor = Color(nsColor: .separatorColor).opacity(0.3)
        static let shadowColor = Color.black.opacity(0.2)
        static let shadowRadius: CGFloat = 16
        static let shadowX: CGFloat = 0
        static let shadowY: CGFloat = 4
    }
}

// MARK: - ViewModel Preview Extension

extension PreviewPanelViewModel {
    static var preview: PreviewPanelViewModel {
        let vm = PreviewPanelViewModel()
        // TODO: 设置预览数据
        return vm
    }
}
